### ISSUE TITLE
Mandatory to use a RM account to start Screen Share?

### ISSUE THREAD

**Issue by drewsed** [bordaigorl/rmview#103]
Hi,

due to our company data policy, I can not use the remarkable cloud. 

I'm on fw 2.9 and can't start Live View in order to use the original streaming API. Do I need to register my device to a remarkable account to get this option to show up?

**Comment by bordaigorl** [comment]
[I assume by "Live View" you mean the new "Screen Share" feature]
Unfortunately the UI on the tablet only enables the menu to start the "Screen Share" feature, if you connected a remarkable account.
You do **not** however need to have synchronised your documents for the feature to work.
(It looks like they are only using the account data for authentication purposes.)
Since rmview works over USB too, you can connect the account and immediately turn off wifi.
This way you can use the Screen Share feature over USB.
The only risk is that if you re-enable the wifi the tablet would start synching, so if you need connection (e.g. to update the software) you need to remember to first disconnect the account, connect, do your business, then reconnect the account and turn off wifi again.

**Comment by drewsed** [comment]
Thanks @bordaigorl for the detailed explanation. You are right with your assumption, when I first got my device, I think it was called Live View not Screen Share, so sorry for the misleading wording.

What you described is exactly what I wanted to know, and I think my way to go. I will give it a try this evening ;)

**Comment by drewsed** [comment]
It is working fine, thanks again.

**Comment by fancypantalons** [comment]
So am I correct, then, that fallback to the old VNC server solution for 2.9 and above is no longer available and only the ScreenShare client mode will be supported?  Or have I just missed something?

I can't connect my RM their cloud for data protection reasons, and I also have no interest in turning off Wifi as that's how I get content to the device, which means that the ScreenShare client method is unfortunately a non-starter for me. :(

**Comment by bordaigorl** [comment]
@fancypantalons fallbak to VNC server is not an option **at the moment**.
@pl-semiotics is working on it but it's a hard and thankless job, gotta be patient.
It's also possible that rM will try to make it as difficult as possible to make the vnc server feasible as it cuts into their business model.
Since this is the state of affairs I would suggest you bring the issue of ScreenShare access without cloud with remarkable directly. Pressure from their customers could be the only thing that can make things move in the right direction.

**Comment by fancypantalons** [comment]
> @fancypantalons fallbak to VNC server is not an option at the moment.
@pl-semiotics is working on it but it's a hard and thankless job, gotta be patient.

Yup, no problem!  I wasn't sure, from the thread here, what the situation was.  Understanding the VNC server doesn't yet support the latest firmware, obviously there's not much you can do at the moment.

> It's also possible that rM will try to make it as difficult as possible to make the vnc server feasible as it cuts into their business model.
Since this is the state of affairs I would suggest you bring the issue of ScreenShare access without cloud with remarkable directly. Pressure from their customers could be the only thing that can make things move in the right direction.

TBH, I hadn't looked too closely at the subscription service model, and now that I see screen sharing is part of the "premium" tier... yeah... I'm afraid you might be right...
