### ISSUE TITLE
IP address changing

### ISSUE THREAD

**Issue by hwhelchel** [bordaigorl/rmview#20]
Today I went to use `rmview` and it no longer worked. Turns out the IP address of the remarkable had changed on my local network. What's the simplest way to work around this?

Thanks!

**Comment by dstango** [comment]
go to your router and see if you find an option that says: always assign the same IP address to this device.

**Comment by bordaigorl** [comment]
The IP is assigned by the WiFi router, and the tablet as basically no control over how it gets assigned.
If you can, configure your WiFi router to assign a static IP associated with the mac address of the tablet (usually routers show the mac address of the connected devices on their status pages.)
If you can't, then I guess your best bet is to leave the address out from your configuration file so that `rmview` will ask for it every time it starts.
