### ISSUE TITLE
Consider special handling for non-matching host key

### ISSUE THREAD

**Issue by ChrisPattison** [bordaigorl/rmview#25]
Updating the firmware on RM1 apparently changes the host key for the SSH server. We should consider giving special handling to this since it may not be obvious what to do for non-technical users

**Comment by bordaigorl** [comment]
Yes definitely!
I guess our options are:

- propose to add the fingeprint to the known hosts (I think Paramiko has some API for this?)
- propose to switch on the ignore flag in settings

**Comment by ChrisPattison** [comment]
I think I am in favor of proposing adding an (optional?) ignore flag to the settings since we probably shouldn't edit the user's known hosts

**Comment by ChrisPattison** [comment]
Also as it turns out, Paramiko requires the fingerprint to be present in known hosts to connect. I.e. the first time install flow in #14 wouldn't work with a "true" fresh install without extra handling

**Comment by bordaigorl** [comment]
AH! I did add the `insecure_auto_add_host` setting for this very purpose, so that's already an option.
But I forgot to document it.
The point of adding to known hosts is to detect changes of fingerprint that may be caused by a man-in-the-middle attack. This is unlikely to happen unless you are a target, and would be fine to ignore in trusted networks.
But I would not want to have an insecure method as a default.
This is why the setting is called `insecure`. On the other hand, if you add it to the known hosts you can be warned only when something changed, and you'll know if it is because you just updated the tablet, in which case it is safe to overwrite the old fingerprint. Makes sense?

I guess an error message explaining some of this would be very helpful. I'll put it down as something to add.

**Comment by bordaigorl** [comment]
Commit 50a1d07cca added documentation for the new setting

**Comment by ChrisPattison** [comment]
That's a good argument for modifying the known hosts. I suppose we could have some nice yes/no dialogue box to answer the fingerprint key thing and update it although I'm not so familiar with QT

**Comment by bordaigorl** [comment]
Commit 4ebdf585ef61495b559615c45dbc5805a573ad39 now handles this case with prompts to the user.
Modifying known hosts is a bit more involved, I prefer to suggest using ssh manually and follow instructions.
Thanks for the feedback!
