### ISSUE TITLE
Unsupported device error: "Device is reMarkable Prototype 1"

### ISSUE THREAD

**Issue by dpowyslybbe** [bordaigorl/rmview#43]
Hi, I have an rM1 but when launching rmview from the command line after connecting to the device an 'Unsupported Device' error appears stating "The detected device is reMarkable Prototype 1" - see below.

![UnsupportedDevice](https://user-images.githubusercontent.com/61805937/104824540-80ffbd00-584a-11eb-83f2-09529efee8aa.PNG)

 I bought my rM1 well after it was launched so I'd be surprised if it was a prototype. Do you think there anything I can do to get rmview to work on my remarkable?

FYI, just in case it may be relevant, I'm still on update 2.1.1.3.

Thanks,

Dom

**Comment by bordaigorl** [comment]
Oh thanks for reporting this!
Currently rmview detects the device type by looking in `/sys/devices/soc0/machine` but since the values found there are undocumented, we rely on this kinds of reports to get the check right.

To solve your immediate problem, you can change line 235 of `rmview.py` to:

    version = re.fullmatch(r"reMarkable(?: Prototype)? (\d+)(\.\d+)*\n", rmv)

and see if it works then.
If you confirm this works I'll push a fix.

**Comment by dpowyslybbe** [comment]
Yes, thank you so much, it does work. What a superb tool!

Just FYI I opened rmview.py in notepad++ and the line I had to change was 229 - not sure why different tools have different line numbers but it worked nevertheless.

Thanks again!

**Comment by bordaigorl** [comment]
(line number discrepancy was my mistake)
