### ISSUE TITLE
Screen Share on software version 2.10

### ISSUE THREAD

**Issue by pks40** [bordaigorl/rmview#99]
As someone already [mentioned on reddit](https://www.reddit.com/r/RemarkableTablet/comments/pl2547/rmview_now_officially_supports_screenshare/hcaotjt), the connection to Screen Share does not work in software version 2.10. One doesn’t even get an error message, it just gets stuck after displaying "Connecting to ScreenShare".

I know that you (@bordaigorl) already saw the thing on reddit, just wanted to open an issue here as well.

Probably this has something to do with the changes to Screen Share to allow sharing with the proprietary app via USB alone, but I have no idea of how to find out what the problem is. Perhaps some magician like @ddvk (who managed to communicate with Screen Share in the first place) can figure this out?

**Comment by ddvk** [comment]
my first hunch is that they fixed the authentication, which was broken/ignored.

which i didnt implement because...
there are some ids that have to be read from the config, i think the code contains some comments about the algorithm used. also a udp broadcast listener is needed.

ill have to install the update and check it out

**Comment by ddvk** [comment]
it was the authentication

**Comment by pks40** [comment]
Thanks a lot, the fix at #100 works for me! (Apart from the version comparison in c38500b being in the wrong direction, but that's easy to amend.)

**Comment by bordaigorl** [comment]
@pks40 thanks for reporting, the version check is now fixed
